# Generated by Django 4.2.26 on 2025-11-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_creator',
            new_name='is_creatPhotoUploadFormor',
        ),
    ]
