# Generated by Django 4.2.26 on 2025-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_people_present_alter_photo_location_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
